app:
  messages-default: "Default message from config server"
  message-profile: "This is dev profiles"
  message-to-override: "message overwritten by server"
  message-to-override-per-project: "SERVER NOT FIND MESSAGE TO THIS APP"

eureka:
  client:
    service-url:
      #jeden lub więcej po przecinku
      defaultZone: http://localhost:8761/eureka
