app:
  messages-default: "Default message from config server"
  message-profile: "This is prod profiles"

eureka:
  client:
    service-url:
      #jeden lub więcej po przecinku
      defaultZone: http://localhost:8761/eureka
